package firstToTenth;

import java.util.ArrayList;

import main.Util;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 * @author Andreas Scheuss
 *
 */


public class SecondFibonacci {

	/**
	 * We calculate all the Fibonacci-Numbers and then add the even terms.
	 * @param args
	 */
	public static void main(String[] args) {
		
		int sum = 0;
		long time = System.currentTimeMillis();
		ArrayList<Integer> fibonaccis = Util.getFibonaccis(4000000);
		for (Integer tempInteger: fibonaccis) {
			if(tempInteger%2 == 0) {
				sum = sum + tempInteger;
			}
		}
		time = System.currentTimeMillis()-time;
		System.out.println(sum);
		System.out.println("Time needed: " + time + "ms");
	}

	
}
