package firstToTenth;

import java.util.ArrayList;

import main.Util;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 * @author Andreas Scheuss
 *
 */


public class SecondFibonacci {
	public static void main(String[] args) {
		//small test:
		ArrayList<Integer> fibonaccis = Util.getFibonaccis(100);
		assert(fibonaccis.size() == 11);
		
		int sum = 0;
		fibonaccis = Util.getFibonaccis(4000000);
		for (Integer tempInteger: fibonaccis) {
			if(tempInteger%2 == 0) {
				sum = sum + tempInteger;
			}
		}
		System.out.println(sum);
	}

	
}
